version: '3'

services:
  rangelmarco:
    image: nginx:1.17.9-alpine
    build:
      context: . 
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 0:80
    labels:
      - "traefik.http.routers.rangelmarco.rule=Host(`rangelmarco.traefik.me`)"
